config/routes.rb
WithinMeans::Application.routes.draw do
  root to: "users#index"

  resources :users do
    resources :expenses
  end

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
  validates :amount, numericality: true, presence: true
  validates :note, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :expenses
  validates :name, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @expenses = @user.expenses
  end

  def new
    @expense = Expense.new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @expense = @user.expenses.new(expense_params)
    if @expense.save
      respond_to do |format|
        format.html { redirect_to user_expenses_path(@user) }
        format.js
      end
    else
      render 'new_user_expense_path(@user)'
    end
  end


private
  def expense_params
    params.require(:expense).permit(:amount, :note, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Account created"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/_expense.html.erb
<tr>
  <td>$<%= expense.amount %></td>
  <td><%= expense.note %></td>
</tr>

app/views/expenses/_form.html.erb
<%= render("layouts/errors", :object => @expense) %>

<br />
<%= form_for [@user, @expense], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :amount %>
    <%= f.number_field :amount, step: 'any' %>
  </div>
  <div class="form-group">
    <%= f.label :note %>
    <%= f.text_field :note %>
  </div>

  <%= f.submit(:class => "button radius secondary") %>
<% end %>
<br />

app/views/expenses/create.js.erb
$('#new_expense').remove();
$('#new_expense_link').show();
$("tr:contains('TOTAL')").before('<%= j render(@expense) %>');

app/views/expenses/index.html.erb
<% content_for(:title, "#{@user.name} | within means") %>


<h3>this month so far</h3>
<table>
  <thead>
    <tr>
      <th width="100">amount</th>
      <th width="400">note</th>
    </tr>
  </thead>
  <tbody>
    <% if @expenses != nil %>
      <%= render @expenses %>
    <% end %>
    <tr>
      <td><b>TOTAL:</b></td>
      <% if @expenses != nil %>
        <td>
          <% amounts = [] %>
          <% @expenses.each do |expense| %>
            <% amounts << expense.amount %>
          <% end %>
          <b>$<%= amounts.sum %></b>
        </td>
      <% else %>
        <td></td>
      <% end %>
    </tr>
  </tbody>
</table>
<br />

<%= link_to 'Add Expenses', new_user_expense_path(@user), class: 'button small radius secondary', id: 'new_expense_link', remote: true %>

app/views/expenses/new.html.erb
<% content_for(:title, "#{@user.name} | within means") %>

app/views/expenses/new.js.erb
$('#new_expense_link').hide().after('<%= j render("form") %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix the following:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name"><h1><a href="/">within means</a></h1></li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li><a href="#">Users</a></li>
          <li><a href="#">Log In (eventually)</a></li>
          <li><a href="#">Sign Up (eventually)</a></li>
        </ul>
      </section>
    </nav>

    <br />
    <br />

    <div class="row">

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>


      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/_form.html.erb
<%= render("layouts/errors", :object => @user) %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <%= f.submit(:class => "button radius secondary") %>
<% end %>

app/views/users/index.html.erb
<% content_for(:title, "Users | within means") %>



<ul>
  <% @users.each do |user| %>
    <%= link_to "#{user.name}", user_path(user) %>
    <br />
  <% end %>
</ul>

<%= link_to "New User", new_user_path, :class => "button radius secondary"  %>

app/views/users/new.html.erb
<% content_for(:title, "New User | within means") %>


<%= render 'form' %>

app/views/users/show.html.erb
<% content_for(:title, "#{@user.name} | within means") %>

<h2><%= @user.name %></h2>
<br />
<br />

<h3>overview</h3>
<table>
  <thead>
    <tr>
      <th width="200"></th>
      <th width="150">so far</th>
      <th width="150">budgeted amount</th>
      <th width="150">remaining</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>this month</th>
      <td>$$$$</td>
      <td>$$$$</td>
      <td>$$$$</td>
    </tr>
    <tr>
      <th>this year</th>
      <td>$$$$</td>
      <td>$$$$</td>
      <td>$$$$</td>
    </tr>
  </tbody>
</table>
<br />

<%= link_to 'View Expenses', user_expenses_path(@user), class: 'button small radius secondary' %>